### ISSUE TITLE
Additional extension?

### ISSUE THREAD

**Issue by SarahMartell** [GALAHProject/fits-standard#1]
Is it reasonable to add the best-fit synthetic template as a fits extension, in addition to its ccf? This would be useful information in early days, but I'm not sure it would continue to be.

**Comment by andycasey** [comment]
I'm OK with this. Any opposed? /ping @GALAHProject/wg6

**Comment by andycasey** [comment]
Ping @GALAHProject/wg6 -- strong opinions opposing this should be voiced

**Comment by sheliak** [comment]
Hi,

A spectrum before the sky subtraction should be one extension, and 
probably it's sigma as well. If there is a nebula in the field or the 
weather is bad, it is almost impossible to subtract the sky properly. An 
automated pipeline can fail quite badly at this and produce spectra that 
have negative fluxes, for example. It might be better for some analysis 
pipelines to work on a spectrum without the sky subtraction in some 
cases, and at least have a chance to identify or go around the problem.

Janez

**Comment by andycasey** [comment]
@sheliak: I have added in the extension for flux before sky subtraction.

After thinking about @SarahMartell's proposal a little more, I think this may be more problematic than it seems. I think it's absolutely important that we _can easily access_ the best-fit model spectra for any analysis, from any code. There is a **lot** of information there that will help inform us about the reductions and analysis. 

For the CCF initial guess, it is just the closest grid point. I am also producing snapshot images of the initial fits (eg #2), and the information of the best-fit spectrum is stored in the image headers. Keeping the best fit CCF spectrum in each image means a lot of replications of grid point spectra (e.g., a lot of disk space), which otherwise could just be extracted afterwards with a couple of lines of code. So I am inclined to leave the best-fit CCF model out of the individual images, and just put examples of how to reproduce the closest CCF model fit in this repository.

If we went the other way and put in the best model fit from any of the analysis codes, that is at least an extra 5+ (e.g., doubling the number of) extensions: `CCF`, `GUESS`, `Cannon`, `Theremin`, `Oracle`. Plus, there are many ways to skin a cat: I'd like to experiment with different algorithms in Oracle to see what works best, and when `Oracle` is doing MCMC there will be many samples from the posterior to consider.

Instead, I would suggest that we require the analysis codes to send back a full filename path of where their best-fit model spectrum exists. That information can be put into the SQL database, and we could even HTTP link it to the exact path (e.g., at AAO FTP or on [galah.science](http://galah.science)).

What do you think about this plan @SarahMartell? It's a balance between extra disk-space/transfer and the ease in accessing the best-fit models.

**Comment by SarahMartell** [comment]
@andycasey I think you're totally right here.

**Comment by andycasey** [comment]
OK, I will close this issue for the moment. I want to make plots showing the model residuals as a function of distance to the moon during observations, so I will need to re-create a lot of best model fits then. When I do that I will put the examples in this repository, and we can organise similar examples a bit better into a centralised location later on.
